'use client';

import {
  useState,
  useEffect,
  createContext,
  type ReactNode,
  useCallback,
  useRef,
} from 'react';
import type { UserSession } from '@/types/session';
import { startAuthentication, startRegistration } from '@simplewebauthn/browser';
import { AuthApi } from '@/lib/auth-api';
import { useToast } from '@/hooks/use-toast';

interface AuthContextType {
  user: UserSession | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  authError: string | null;
  login: (sessionData: UserSession) => void;
  passkeyLogin: (email: string) => Promise<void>;
  logout: () => void;
  setAuthError: (error: string | null) => void;
}

export const AuthContext = createContext<AuthContextType | null>(null);

const SESSION_STORAGE_KEY = 'staffpro-session';

/**
 * Utility to clean MIME-wrapped binary strings (e.g., =?BINARY?B?...?=)
 * which are sometimes generated by PHP WebAuthn libraries.
 */
function cleanBinaryString(val: any): any {
  if (typeof val === 'string' && val.startsWith('=?BINARY?B?')) {
    return val.replace('=?BINARY?B?', '').replace('?=', '');
  }
  return val;
}

/**
 * Surgically cleans the options object for WebAuthn to satisfy strict library validation.
 * It whitelists only standard keys and handles known platform/PHP-specific non-standardisms.
 */
function prepareWebAuthnOptions(obj: any): any {
  if (!obj || typeof obj !== 'object') return obj;

  if (Array.isArray(obj)) {
    return obj.map(prepareWebAuthnOptions);
  }

  const cleaned: any = {};
  // List of standard WebAuthn keys for Creation and Request options
  const allowedKeys = [
    'rp', 'user', 'challenge', 'pubKeyCredParams', 'timeout', 
    'excludeCredentials', 'authenticatorSelection', 'attestation', 
    'extensions', 'allowCredentials', 'userVerification'
  ];

  for (const key of allowedKeys) {
    if (obj[key] !== undefined) {
      let value = obj[key];
      
      // Clean binary fields known to use the binary wrapper
      if (key === 'challenge' || key === 'id') {
        value = cleanBinaryString(value);
      } else if (typeof value === 'object') {
        value = prepareWebAuthnOptions(value);
      }
      
      cleaned[key] = value;
    }
  }

  // FIX: rp.id must be a valid domain. If it's the placeholder, use the current hostname.
  if (cleaned.rp && (cleaned.rp.id === 'staffpro_mobile' || !cleaned.rp.id) && typeof window !== 'undefined') {
    cleaned.rp.id = window.location.hostname;
    console.log(`PASSKEY: Overriding RP ID to current hostname: ${cleaned.rp.id}`);
  }
  
  // FIX: Remove non-standard "exts" key from extensions which triggers the library warning
  if (cleaned.extensions && cleaned.extensions.exts !== undefined) {
    delete cleaned.extensions.exts;
    // If extensions is now empty, remove it entirely
    if (Object.keys(cleaned.extensions).length === 0) {
      delete cleaned.extensions;
    }
  }

  return cleaned;
}

function getDeviceName(): string {
  if (typeof window === 'undefined') return 'Unknown';
  const ua = window.navigator.userAgent;
  if (/iPad|iPhone|iPod/.test(ua)) return 'iOS Device';
  if (/Android/.test(ua)) return 'Android Device';
  if (/Macintosh/.test(ua)) return 'Mac';
  if (/Windows/.test(ua)) return 'Windows PC';
  if (/Linux/.test(ua)) return 'Linux Device';
  return 'Mobile/Web Browser';
}

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<UserSession | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [authError, setAuthError] = useState<string | null>(null);
  const { toast } = useToast();
  const isAuthenticated = !!user;

  const login = useCallback((sessionData: UserSession) => {
    setUser(sessionData);
    setAuthError(null);
    try {
      localStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(sessionData));
    } catch (error) {
      console.error('AUTH: Failed to persist session.');
    }
  }, []);

  const logout = useCallback(() => {
    try {
      localStorage.removeItem(SESSION_STORAGE_KEY);
    } catch (error) {
      console.error('AUTH: Error clearing storage:', error);
    }
    setUser(null);
    setAuthError(null);
    if (typeof window !== 'undefined') {
      window.location.replace(window.location.origin);
    }
  }, []);

  const logoutRef = useRef(logout);
  const loginRef = useRef(login);

  useEffect(() => {
    logoutRef.current = logout;
    loginRef.current = login;
  }, [logout, login]);

  useEffect(() => {
    const handleServerMessage = (event: MessageEvent) => {
      let data = event.data;
      if (typeof data === 'string') {
        try {
          const jsonMatch = data.match(/\{.*\}/);
          if (jsonMatch) data = JSON.parse(jsonMatch[0]);
          else return;
        } catch (e) { return; }
      }
      if (!data || typeof data !== 'object') return;

      const status = data.status ? String(data.status).toLowerCase() : '';
      const purpose = data.purpose ? String(data.purpose).toLowerCase() : '';

      if (status === 'logoff' || purpose === 'logoff') {
        logoutRef.current();
        return;
      }
      
      if (status === 'fail' || (status === 'success' && (purpose.includes('invalid') || purpose.includes('error')))) {
        setAuthError('invalid-code');
        return;
      }

      if (status === 'success') {
        const isActuallyAuthenticated = purpose === 'authenticated' || (purpose.includes('verify') && !purpose.includes('email'));
        if (isActuallyAuthenticated) {
          loginRef.current({ ...data, method: 'code' });
        }
      }
    };

    window.addEventListener('message', handleServerMessage);
    return () => window.removeEventListener('message', handleServerMessage);
  }, []);

  useEffect(() => {
    try {
      const sessionString = localStorage.getItem(SESSION_STORAGE_KEY);
      if (sessionString) {
        const session = JSON.parse(sessionString);
        if (session.status === 'success') setUser(session);
      }
    } catch (error) {
      localStorage.removeItem(SESSION_STORAGE_KEY);
    } finally {
      setIsLoading(false);
    }
  }, []);

  const passkeyLogin = useCallback(async (email: string) => {
    try {
      setAuthError(null);
      const deviceName = getDeviceName();
      const responseData = await AuthApi.getPasskeyOptions(email, deviceName);
      
      // 1. Unwrap and Surgically Clean the options
      let rawOptions = responseData.publicKey || responseData;
      let options = prepareWebAuthnOptions(rawOptions);
      
      console.log('PASSKEY: Ceremony Options Object (Final Cleaned):', JSON.stringify(options, null, 2));

      if (!options.challenge) {
        throw new Error('Server response missing "challenge" property.');
      }

      let credentialResponse;
      // Detect if this is Registration (user + params) or Authentication (allowCredentials)
      const isRegistration = !!(options.user && options.pubKeyCredParams);
      
      if (isRegistration) {
        console.log('PASSKEY: Detected Registration Options. Starting registration ceremony...');
        credentialResponse = await startRegistration(options);
      } else {
        console.log('PASSKEY: Detected Authentication Options. Starting authentication ceremony...');
        credentialResponse = await startAuthentication(options);
      }
      
      const result = await AuthApi.verifyPasskey(credentialResponse, email, deviceName);
      
      if (result.status === 'success') {
        login({ ...result, method: 'passkey' });
      } else {
        throw new Error(result.purpose || 'Passkey verification failed.');
      }
    } catch (error: any) {
      console.error('PASSKEY: Error in passkeyLogin flow:', error);
      let errorMessage = error.message || 'Could not sign in with passkey.';
      if (error.name === 'NotAllowedError') errorMessage = 'Passkey authentication was cancelled or timed out.';
      else if (error.name === 'SecurityError') errorMessage = `Security Error: The RP ID "${window.location.hostname}" must match the origin.`;
      
      toast({
        title: 'Authentication Failed',
        description: errorMessage,
        variant: 'destructive',
      });
    }
  }, [login, toast]);

  return (
    <AuthContext.Provider
      value={{ user, isAuthenticated, isLoading, authError, login, passkeyLogin, logout, setAuthError }}
    >
      {children}
    </AuthContext.Provider>
  );
}
